#!/bin/bash

srcdir='src/'
objdir='bin-obj/release/'
bindir='bin/release/'
appname='builder'

function _compile {
        printf '\x1b[32m'
        printf 'gcc -o '${objdir}${1}'.o -Wall -Wextra -D_RELEASE -Iinclude -Isrc -O2 -c '${srcdir}${1}'.c\n\x1b[0m'
                gcc -o  ${objdir}${1}.o  -Wall -Wextra -D_RELEASE -Iinclude -Isrc -O2 -c  ${srcdir}${1}.c
                if [ $? -ne 0 ]; then exit 1; fi
}

function _link {
        printf '\x1b[32m'
        printf 'gcc -o '${bindir}${appname}' -Wall -Wextra -Llib '${objdir}${1}' -lpthread\n\x1b[0m'
                gcc -o  ${bindir}${appname}  -Wall -Wextra -Llib  ${objdir}${1}  -lpthread
                if [ $? -ne 0 ]; then exit 1; fi
}

cd ..

printf '\x1b[32;1m'
printf 'Starting\n\n'
printf 'Compiling:\n'
printf '\x1b[0m'
printf '\x1b[32m'

_compile application

printf '\n\x1b[32;1m'
printf 'Linking:\n'

_link *.o

printf '\n\x1b[32;1m'
printf 'Done\n'
printf '\x1b[0m'

cd cmd