#!/bin/bash
cd ..

printf '\x1b[32;1m'
printf 'Starting...\n'
printf 'Compiling:\n'
printf '\x1b[0m'
printf '\x1b[32m'
printf 'gcc -o bin-obj/debug/application.o                    -Wall -Wextra -D_DEBUG -Iinclude -Isrc -Isrc/dependencies -Wall -Og -g3 -c src/application.c\n\x1b[0m'
        gcc -o bin-obj/debug/application.o                    -Wall -Wextra -D_DEBUG -Iinclude -Isrc -Isrc/dependencies -Wall -Og -g3 -c src/application.c
      
        mkdir bin-obj/debug/renderer 2> /dev/null
printf '\x1b[32m'
printf 'gcc -o bin-obj/debug/renderer/renderer.o              -Wall -Wextra -D_DEBUG -Iinclude -Isrc -Isrc/dependencies -Wall -Og -g3 -c src/renderer/renderer.c\n\x1b[0m'
        gcc -o bin-obj/debug/renderer/renderer.o              -Wall -Wextra -D_DEBUG -Iinclude -Isrc -Isrc/dependencies -Wall -Og -g3 -c src/renderer/renderer.c
      
        mkdir bin-obj/debug/dependencies       2> /dev/null
        mkdir bin-obj/debug/dependencies/nodes 2> /dev/null
printf '\x1b[32m'
printf 'gcc -o bin-obj/debug/dependencies/nodes/stdlog.o      -Wall -Wextra -D_DEBUG -Iinclude -Isrc -Isrc/dependencies -Wall -Og -g3 -c src/dependencies/nodes/stdlog.c\n\x1b[0m'
        gcc -o bin-obj/debug/dependencies/nodes/stdlog.o      -Wall -Wextra -D_DEBUG -Iinclude -Isrc -Isrc/dependencies -Wall -Og -g3 -c src/dependencies/nodes/stdlog.c
printf '\x1b[32m'
printf 'gcc -o bin-obj/debug/dependencies/nodes/node.o        -Wall -Wextra -D_DEBUG -Iinclude -Isrc -Isrc/dependencies -Wall -Og -g3 -c src/dependencies/nodes/node.c\n\x1b[0m'
        gcc -o bin-obj/debug/dependencies/nodes/node.o        -Wall -Wextra -D_DEBUG -Iinclude -Isrc -Isrc/dependencies -Wall -Og -g3 -c src/dependencies/nodes/node.c
printf '\x1b[32m'
printf 'gcc -o bin-obj/debug/dependencies/nodes/advencenode.o -Wall -Wextra -D_DEBUG -Iinclude -Isrc -Isrc/dependencies -Wall -Og -g3 -c src/dependencies/nodes/advencenode.c\n\x1b[0m'
        gcc -o bin-obj/debug/dependencies/nodes/advencenode.o -Wall -Wextra -D_DEBUG -Iinclude -Isrc -Isrc/dependencies -Wall -Og -g3 -c src/dependencies/nodes/advencenode.c
printf '\x1b[32m'
printf 'gcc -o bin-obj/debug/dependencies/nodes/stdtime.o     -Wall -Wextra -D_DEBUG -Iinclude -Isrc -Isrc/dependencies -Wall -Og -g3 -c src/dependencies/nodes/stdtime.c\n\x1b[0m'
        gcc -o bin-obj/debug/dependencies/nodes/stdtime.o     -Wall -Wextra -D_DEBUG -Iinclude -Isrc -Isrc/dependencies -Wall -Og -g3 -c src/dependencies/nodes/stdtime.c

printf '\n\x1b[32;1m'
printf 'Linking:\n'
printf '\x1b[0m'
printf '\x1b[32m'
printf 'gcc -o bin/debug/application -Wall -Wextra -Llib bin-obj/debug/application.o bin-obj/debug/renderer/renderer.o bin-obj/debug/dependencies/nodes/* -lm -ldl -lGL -lGLU -lGLEW -lglfw /* -lcimgui */\n\x1b[0m'
        gcc -o bin/debug/application -Wall -Wextra -Llib bin-obj/debug/application.o bin-obj/debug/renderer/renderer.o bin-obj/debug/dependencies/nodes/* -lm -ldl -lGL -lGLU -lGLEW -lglfw

        cp -rf rcs bin/debug/ 2> /dev/null

printf '\n\x1b[32;1m'
printf 'Done.\n'
printf '\x1b[0m'

cd cmd