#!/bin/bash

srcdir='src/'
objdir='bin-obj/release/'
bindir='bin/release/'
appname='nodes'

function _compile {
        printf '\x1b[32m'
        printf "gcc -o ${objdir}${1}.o -Wall -Wextra -D_RELEASE -Iinclude -Isrc -O2 -c ${srcdir}${1}.c\n\x1b[0m"
                gcc -o ${objdir}${1}.o -Wall -Wextra -D_RELEASE -Iinclude -Isrc -O2 -c ${srcdir}${1}.c
                if [ ${?} -ne 0 ]; then exit 1; fi
}

function _link {
        printf '\x1b[32m'
        printf "gcc -o ${bindir}${appname} -Wall -Wextra -Llib ${@} -lpthread\n\x1b[0m"
                gcc -o ${bindir}${appname} -Wall -Wextra -Llib ${@} -lpthread
                if [ ${?} -ne 0 ]; then exit 1; fi
}

cd ..

printf '\x1b[32;1m'
printf 'Starting\n\n'
printf 'Compiling:\n'
printf '\x1b[0m'
printf '\x1b[32m'

_compile application
_compile algebra

printf '\n\x1b[32;1m'
printf 'Linking:\n'

_link ${objdir}*.o
cp -rf rcs ${bindir} 2> /dev/null

printf '\n\x1b[32;1m'
printf 'Done\n'
printf '\x1b[0m'

cd cmd