.PHONY: clean All

All:
	@echo "----------Building project:[ cherno - Debug ]----------"
	@"$(MAKE)" -f  "cherno.mk"
clean:
	@echo "----------Cleaning project:[ cherno - Debug ]----------"
	@"$(MAKE)" -f  "cherno.mk" clean
