#!/bin/bash

srcdir='src/'
objdir='bin-obj/debug/'
bindir='bin/debug/'
appname='calculator'

function _compile {
        printf '\x1b[32m'
        printf "gcc -o ${objdir}${1}.o -Wall -Wextra -D_DEBUG -Iinclude -Isrc -Og -g3 -save-temps=obj -c ${srcdir}${1}.c\n\x1b[0m"
                gcc -o ${objdir}${1}.o -Wall -Wextra -D_DEBUG -Iinclude -Isrc -Og -g3 -save-temps=obj -c ${srcdir}${1}.c
                if [ ${?} -ne 0 ]; then exit 1; fi
}

function _link {
        printf '\x1b[32m'
        printf "gcc -o ${bindir}${appname} -Wall -Wextra -Llib ${@} -lm -ldl -lpthread\n\x1b[0m"
                gcc -o ${bindir}${appname} -Wall -Wextra -Llib ${@} -lm -ldl -lpthread
                if [ ${?} -ne 0 ]; then exit 1; fi
}

cd ..

printf '\x1b[32;1m'
printf 'Starting\n\n'
printf 'Compiling:\n'
printf '\x1b[0m'
# printf '\x1b[32m'

_compile application
_compile bignum
_compile parser
_compile stdlog
_compile stdmath
_compile stdtime

printf '\n\x1b[32;1m'
printf 'Linking:\n'

_link ${objdir}*.o

printf '\n\n\x1b[32;1m'
printf 'Done\n'
printf '\x1b[0m'

cd cmd