#!/bin/bash

echo 'g++ -o triangle main.cpp -ldl -l_glad -lglfw -Wall -O3 -s'
      g++ -o triangle main.cpp -ldl -l_glad -lglfw -Wall -O3 -s

echo './triangle'
      LD_LIBRARY_PATH=/usr/local/lib $(pwd)/triangle
