#!/bin/bash
cd ..

printf '\x1b[32;1m'
printf 'Starting...\n'
printf 'Compiling:\n'
printf '\x1b[0m'
printf '\x1b[32m'
printf 'gcc -o bin-obj/release/application.o -Wall -Wextra -D_RELEASE -Iinclude -Isrc -Wall -O2 -m64 -c src/application.c\n\x1b[0m'
        gcc -o bin-obj/release/application.o -Wall -Wextra -D_RELEASE -Iinclude -Isrc -Wall -O2 -m64 -c src/application.c

        mkdir bin-obj/release/renderer 2> /dev/null
printf '\x1b[32m'
printf 'gcc -o bin-obj/release/renderer/renderer.o -Wall -Wextra -D_RELEASE -Iinclude -Isrc -Wall -Og -g3 -m64 -c src/renderer/renderer.c\n\x1b[0m'
        gcc -o bin-obj/release/renderer/renderer.o -Wall -Wextra -D_RELEASE -Iinclude -Isrc -Wall -Og -g3 -m64 -c src/renderer/renderer.c

printf '\n\x1b[32;1m'
printf 'Linking:\n'
printf '\x1b[0m'
printf '\x1b[32m'
printf 'gcc -o bin/release/application -Wall -Wextra -m64 -Llib -s bin-obj/release/application.o bin-obj/release/renderer/renderer.o -lm -ldl -lGL -lGLU -lGLEW -lglfw /* -lcimgui */\n\x1b[0m'
        gcc -o bin/release/application -Wall -Wextra -m64 -Llib -s bin-obj/release/application.o bin-obj/release/renderer/renderer.o -lm -ldl -lGL -lGLU -lGLEW -lglfw

        cp -rf rcs bin/release/ 2> /dev/null

printf '\n\x1b[32;1m'
printf 'Done.\n'
printf '\x1b[0m'

cd cmd